### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by ywjawmw** [mysbupt/CrossCBR#1]
CrossCBR_A:  using the negative cross-view cosine similarity to replace the contrastive loss
I can't understand why this setting can enlarge the cross-view alignment, could you give me more detail setting information? 
By the way, I think this may be  "using the **positive** cross-view cosine similarity to replace the contrastive loss".
I look forward to your reply!

**Comment by mysbupt** [comment]
Thanks for the question. Actually, the "negative" here means a "negative number" (负数), instead of "negative samples". Since the range of a cosine similarity score is within [-1, 1], when we take the negative of a cosine similarity as the regularization term (loss), we hope the cosine similarity score can approach 1 (the cross-view affinity increases) when the loss is suppressed.

Hope this answers your question. Welcome for further discussion!

**Comment by ywjawmw** [comment]
Got it! Thanks for your reply. I understanded it very clearly.

**Comment by ywjawmw** [comment]
Got it! Thanks for your reply. I understood it very clearly.
